-- Criar tabela de ideias
CREATE TABLE ideias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conteudo TEXT NOT NULL,
  chat_id BIGINT NOT NULL,
  tipo TEXT DEFAULT 'ideia',
  resumo TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Criar tabela de brainstorms
CREATE TABLE brainstorms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ideia_id BIGINT REFERENCES ideias(id) ON DELETE CASCADE,
  conteudo TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Desativar RLS para permitir acesso público completo
ALTER TABLE ideias DISABLE ROW LEVEL SECURITY;
ALTER TABLE brainstorms DISABLE ROW LEVEL SECURITY;

-- Índices para melhorar a performance
CREATE INDEX idx_ideias_chat_id ON ideias(chat_id);
CREATE INDEX idx_brainstorms_ideia_id ON brainstorms(ideia_id);

-- Comentários para documentação
COMMENT ON TABLE ideias IS 'Armazena as ideias dos usuários do bot Cerebro';
COMMENT ON TABLE brainstorms IS 'Armazena os brainstorms gerados para as ideias';
COMMENT ON COLUMN ideias.chat_id IS 'ID do chat do Telegram do usuário';
COMMENT ON COLUMN ideias.tipo IS 'Tipo da mensagem (ideia, questão, etc)';
COMMENT ON COLUMN ideias.resumo IS 'Resumo ou categoria da ideia';
COMMENT ON COLUMN brainstorms.ideia_id IS 'Referência à ideia para a qual o brainstorm foi gerado';
