-- Criar tabela de ideias
CREATE TABLE ideias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conteudo TEXT NOT NULL,
  chat_id BIGINT NOT NULL,
  tipo TEXT DEFAULT 'ideia',
  resumo TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Criar tabela de brainstorms
CREATE TABLE brainstorms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ideia_id BIGINT REFERENCES ideias(id) ON DELETE CASCADE,
  conteudo TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Adicionar políticas de segurança (RLS)
ALTER TABLE ideias ENABLE ROW LEVEL SECURITY;
ALTER TABLE brainstorms ENABLE ROW LEVEL SECURITY;

-- Política para permitir que qualquer usuário autenticado insira dados
CREATE POLICY "Permitir inserção de ideias" ON ideias 
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir inserção de brainstorms" ON brainstorms 
  FOR INSERT WITH CHECK (true);

-- Política para permitir que usuários vejam apenas suas próprias ideias
CREATE POLICY "Usuários veem apenas suas próprias ideias" ON ideias 
  FOR SELECT USING (
    auth.uid()::TEXT = chat_id::TEXT
    OR auth.uid()::TEXT IN (SELECT jsonb_array_elements_text(auth.jwt() -> 'app_metadata' -> 'superuser'))
  );

-- Política para permitir que usuários vejam apenas brainstorms de suas próprias ideias
CREATE POLICY "Usuários veem apenas brainstorms de suas ideias" ON brainstorms 
  FOR SELECT USING (
    ideia_id IN (
      SELECT id FROM ideias 
      WHERE chat_id::TEXT = auth.uid()::TEXT
      OR auth.uid()::TEXT IN (SELECT jsonb_array_elements_text(auth.jwt() -> 'app_metadata' -> 'superuser'))
    )
  );

-- Política para permitir que usuários apaguem apenas suas próprias ideias
CREATE POLICY "Usuários apagam apenas suas próprias ideias" ON ideias 
  FOR DELETE USING (
    chat_id::TEXT = auth.uid()::TEXT
    OR auth.uid()::TEXT IN (SELECT jsonb_array_elements_text(auth.jwt() -> 'app_metadata' -> 'superuser'))
  );

-- Política para permitir que usuários apaguem apenas brainstorms de suas próprias ideias
CREATE POLICY "Usuários apagam apenas brainstorms de suas ideias" ON brainstorms 
  FOR DELETE USING (
    ideia_id IN (
      SELECT id FROM ideias 
      WHERE chat_id::TEXT = auth.uid()::TEXT
      OR auth.uid()::TEXT IN (SELECT jsonb_array_elements_text(auth.jwt() -> 'app_metadata' -> 'superuser'))
    )
  );

-- Índices para melhorar a performance
CREATE INDEX idx_ideias_chat_id ON ideias(chat_id);
CREATE INDEX idx_brainstorms_ideia_id ON brainstorms(ideia_id);

-- Comentários para documentação
COMMENT ON TABLE ideias IS 'Armazena as ideias dos usuários do bot Cerebro';
COMMENT ON TABLE brainstorms IS 'Armazena os brainstorms gerados para as ideias';
COMMENT ON COLUMN ideias.chat_id IS 'ID do chat do Telegram do usuário';
COMMENT ON COLUMN ideias.tipo IS 'Tipo da mensagem (ideia, questão, etc)';
COMMENT ON COLUMN ideias.resumo IS 'Resumo ou categoria da ideia';
COMMENT ON COLUMN brainstorms.ideia_id IS 'Referência à ideia para a qual o brainstorm foi gerado';
